Added Professor Class
DevDogs-UGA/Optimal-Schedule-Builder pull request #54
Opened 2024-09-27 18:45 UTC by YuvalDeshe

Added the Professor class to be used in webscraping; #21

2024-09-27 18:56 UTC, Jeffrey-000 commented
some issues:
-create class constructors
-change the class property visibility to private; currently is package protected
-create necessary getters and setters
-specifically line 11 note: setting the values of the array should be done by a constructor and after the variables have be initialized

2024-09-27 20:48 UTC, YuvalDeshe commented
The commit 07510e0:
 - Added 3 constructors.
 - Made all variables within the class private.
 - Created a getter and a setter method for each variable (two setters for ratingDistribution).
 - Added documentation for each method.

2024-09-28 18:30 UTC, Jeffrey-000 requested changes

2024-09-28 18:30 UTC, Jeffrey-000 commented on backend/webscraping/Professor.java
> +        name = this.name;
the variables are in the wrong order
should be --> this.name = name;

2024-09-28 18:53 UTC, YuvalDeshe commented
The commit 40de972 fixed the order of the variables.

2024-09-30 18:44 UTC, YuvalDeshe commented
The commits 1de790b and b53cf0a moved the file to the correct directory according to the new file structure and added Professor.java to the `edu.uga.devdogs.professor_rating.webscraping` package.

2024-09-30 19:21 UTC, merged